### ISSUE TITLE
Работник в отрядом кс

### ISSUE THREAD

**Issue by mariiamanuylova** [spbso/vk-mini-so#10]
КС Штаба. КС отряда. 
При редактировании должности КС моего отряда, есть вариант «работник» ![Screenshot_2022-03-11-01-47-07-956_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/157894914-099480df-b4ee-424c-a9d2-fb67d9d724c5.jpg)

**Comment by VMatyagin** [comment]
пофикшено

**Comment by mariiamanuylova** [comment]
![Screenshot_2022-05-08-15-44-45-163_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/167296806-dbc6f491-d91f-4578-8334-d6b075738720.jpg)

Ок
