### ISSUE TITLE
Убрать заглавные буквы в направлениях

### ISSUE THREAD

**Issue by mariiamanuylova** [spbso/vk-mini-so#22]
Студенческие педагогические отряды
Студенческие строительные отряды
... 

![Screenshot_2022-04-04-21-06-47-885_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/161604828-d75e66e1-8880-4b94-a5f5-bbbbc3453910.jpg)

**Comment by VMatyagin** [comment]
отредачил бд

**Comment by mariiamanuylova** [comment]
![Screenshot_2022-05-08-15-53-46-369_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/167297096-656ba1db-e206-40f7-9376-ace6aa1eada2.jpg)

Ок
