### ISSUE TITLE
Разрешение на уведомления

### ISSUE THREAD

**Issue by mariiamanuylova** [spbso/vk-mini-so#25]
Изначально уведомления включены
Если их отключить, то при желании снова включить, появляется запрос на разрешение
Почему его нет изначально? 
Или тогда почему он есть при повторном включении? 

Уведомления приходят не в вк, а внутри приложения. 

![Screenshot_2022-04-04-21-31-11-115_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/161609081-9c404b44-921f-4f0a-8fd2-1f148e5274f8.jpg)
![Screenshot_2022-04-04-21-31-20-240_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/161609104-1a4decee-8eac-49ad-b3e8-4d5f70228767.jpg)

**Comment by VMatyagin** [comment]
Я, пожалуй, выпилю этот функционал из приложения. Эти разрешение на отправку нативных уведомлений. Нам пока не нужно
