### ISSUE TITLE
При создании меро нельзя создать конкурс
Если редактировать меро, то можно
Не выводится ошибки что не так

### ISSUE THREAD

**Issue by mariiamanuylova** [spbso/vk-mini-so#45]
![DXcmSPX6qOADUGCfWGnw4_wbtdab83Z-66E60NRYsbm1TNqkDSl-dVdFhzm5GoQkdKZrW95awdLKi1rJ7bJavjoY.jpg](https://user-images.githubusercontent.com/22224425/168498803-dd40412a-2bcd-4545-8efd-1813cc13f05d.jpg)

**Comment by mariiamanuylova** [comment]
При нажатии на кнопку создать ничего не происходит, при возврате назад всё внесённые данные стираются

**Comment by VMatyagin** [comment]
это логично, потому что мероприятия еще не создано. скрою кнопку
