### ISSUE TITLE
Create event. Impossible to create

### ISSUE THREAD

**Issue by mariiamanuylova** [spbso/vk-mini-so#5]
![Screenshot_2022-03-11-17-01-29-070_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/157888855-3cb2aa03-5fde-4c6d-8cd8-d7e8ef24fc24.jpg)

**Comment by VMatyagin** [comment]
Кажется, что уже решено

**Comment by mariiamanuylova** [comment]
![Screenshot_2022-05-08-15-41-26-650_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/167296636-541b03b9-c0c8-4a96-8916-b07e52b14f4c.jpg)

Не решено
