### ISSUE TITLE
Невозможно создать конкурс в мероприятии

### ISSUE THREAD

**Issue by mariiamanuylova** [spbso/vk-mini-so#6]
КС Штаба
После нажатия кнопки создать ничего не происходит![Screenshot_2022-03-11-17-05-13-854_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/157892649-5f4de50b-b4a2-4515-bf83-4e0566de38b8.jpg)

**Comment by VMatyagin** [comment]
вероятно пофикшено

**Comment by mariiamanuylova** [comment]
Снова не работает
