### ISSUE TITLE
Создание мероприятия в прошлом

### ISSUE THREAD

**Issue by mariiamanuylova** [spbso/vk-mini-so#8]
КС Штаба. Создание меро. 
Можно создать мероприятие в прошлом ![Screenshot_2022-03-11-17-04-33-534_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/157894034-354e0e64-9862-47f2-a976-60b0ae5738ec.jpg)

**Comment by VMatyagin** [comment]
на текущий момент это фича, дальше нужно будет убирать такую возможность
