### ISSUE TITLE
Выбор любого штаба при создании мероприятия

### ISSUE THREAD

**Issue by mariiamanuylova** [spbso/vk-mini-so#9]
КС Штаба. Создание меро. 
Могу выбрать любой штаб при создании мероприятия, вне зависимости имею я к нему отношение или нет. ![Screenshot_2022-03-11-17-01-29-070_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/157894483-6e1c574c-9d5f-455b-8963-081401e44550.jpg)

**Comment by VMatyagin** [comment]
пофикшено

**Comment by mariiamanuylova** [comment]
![Screenshot_2022-05-08-15-40-09-289_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/22224425/167296574-b1f287ac-68e2-4669-a64f-ea6e88b8126b.jpg)

Ок
